// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';
import {main} from '../models';

export function ClearChat():Promise<void>;

export function GetCostSummary():Promise<llm.CostSummary>;

export function GetDefaultModel():Promise<string>;

export function GetModels():Promise<Array<string>>;

export function GetProvider():Promise<string>;

export function GetProviders():Promise<Array<string>>;

export function HasAPIKey():Promise<boolean>;

export function OpenAIIsLoggedIn():Promise<boolean>;

export function OpenAILogin():Promise<string>;

export function ResetCosts():Promise<void>;

export function SendMessage(arg1:string):Promise<main.ChatResponse>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetProvider(arg1:string):Promise<void>;
