// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function GetCostSummary() {
  return window['go']['main']['App']['GetCostSummary']();
}

export function GetDefaultModel() {
  return window['go']['main']['App']['GetDefaultModel']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetProvider() {
  return window['go']['main']['App']['GetProvider']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function OpenAIIsLoggedIn() {
  return window['go']['main']['App']['OpenAIIsLoggedIn']();
}

export function OpenAILogin() {
  return window['go']['main']['App']['OpenAILogin']();
}

export function ResetCosts() {
  return window['go']['main']['App']['ResetCosts']();
}

export function RespondPermission(arg1, arg2) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetProvider(arg1) {
  return window['go']['main']['App']['SetProvider'](arg1);
}
