// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CallMCPTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallMCPTool'](arg1, arg2, arg3);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetCostSummary() {
  return window['go']['main']['App']['GetCostSummary']();
}

export function GetDefaultModel() {
  return window['go']['main']['App']['GetDefaultModel']();
}

export function GetEventSources() {
  return window['go']['main']['App']['GetEventSources']();
}

export function GetEventStats() {
  return window['go']['main']['App']['GetEventStats']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetProvider() {
  return window['go']['main']['App']['GetProvider']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetWatchedChats() {
  return window['go']['main']['App']['GetWatchedChats']();
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function OpenAIIsLoggedIn() {
  return window['go']['main']['App']['OpenAIIsLoggedIn']();
}

export function OpenAILogin() {
  return window['go']['main']['App']['OpenAILogin']();
}

export function ReloadRules() {
  return window['go']['main']['App']['ReloadRules']();
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function ResetCosts() {
  return window['go']['main']['App']['ResetCosts']();
}

export function RespondPermission(arg1, arg2) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetProvider(arg1) {
  return window['go']['main']['App']['SetProvider'](arg1);
}

export function UnwatchChat(arg1) {
  return window['go']['main']['App']['UnwatchChat'](arg1);
}

export function WatchChat(arg1) {
  return window['go']['main']['App']['WatchChat'](arg1);
}
