// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CallMCPTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallMCPTool'](arg1, arg2, arg3);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetAudioDevice() {
  return window['go']['main']['App']['GetAudioDevice']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetCostSummary() {
  return window['go']['main']['App']['GetCostSummary']();
}

export function GetDefaultModel() {
  return window['go']['main']['App']['GetDefaultModel']();
}

export function GetEventSources() {
  return window['go']['main']['App']['GetEventSources']();
}

export function GetEventStats() {
  return window['go']['main']['App']['GetEventStats']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetNotificationsEnabled() {
  return window['go']['main']['App']['GetNotificationsEnabled']();
}

export function GetProvider() {
  return window['go']['main']['App']['GetProvider']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSTTLanguage() {
  return window['go']['main']['App']['GetSTTLanguage']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetTTSVoice() {
  return window['go']['main']['App']['GetTTSVoice']();
}

export function GetVoiceEnabled() {
  return window['go']['main']['App']['GetVoiceEnabled']();
}

export function GetWatchedChats() {
  return window['go']['main']['App']['GetWatchedChats']();
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function OpenAIIsLoggedIn() {
  return window['go']['main']['App']['OpenAIIsLoggedIn']();
}

export function OpenAILogin() {
  return window['go']['main']['App']['OpenAILogin']();
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function ResetCosts() {
  return window['go']['main']['App']['ResetCosts']();
}

export function RespondPermission(arg1, arg2) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetAudioDevice(arg1) {
  return window['go']['main']['App']['SetAudioDevice'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetProvider(arg1) {
  return window['go']['main']['App']['SetProvider'](arg1);
}

export function SetSTTLanguage(arg1) {
  return window['go']['main']['App']['SetSTTLanguage'](arg1);
}

export function SetTTSVoice(arg1) {
  return window['go']['main']['App']['SetTTSVoice'](arg1);
}

export function SetVoiceEnabled(arg1) {
  return window['go']['main']['App']['SetVoiceEnabled'](arg1);
}

export function SpeakText(arg1) {
  return window['go']['main']['App']['SpeakText'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function ToggleNotifications(arg1) {
  return window['go']['main']['App']['ToggleNotifications'](arg1);
}

export function TrackSentMessageID(arg1) {
  return window['go']['main']['App']['TrackSentMessageID'](arg1);
}

export function TranscribeAudio(arg1) {
  return window['go']['main']['App']['TranscribeAudio'](arg1);
}

export function UnwatchChat(arg1) {
  return window['go']['main']['App']['UnwatchChat'](arg1);
}

export function WatchChat(arg1) {
  return window['go']['main']['App']['WatchChat'](arg1);
}
