// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {voice} from '../models';
import {llm} from '../models';
import {eventbus} from '../models';
import {marketplace} from '../models';
import {agent} from '../models';

export function AbortAgent():Promise<void>;

export function AddMCPServer(arg1:string,arg2:string,arg3:Array<string>,arg4:Record<string, string>,arg5:boolean,arg6:Array<string>,arg7:string):Promise<string>;

export function ApplyUpdate(arg1:string):Promise<string>;

export function AuthMCPServer(arg1:string):Promise<string>;

export function CallMCPTool(arg1:string,arg2:string,arg3:Record<string, string>):Promise<string>;

export function CheckComputerUseDeps():Promise<string>;

export function CheckNpx():Promise<boolean>;

export function ClearChat():Promise<void>;

export function DeleteSession(arg1:string):Promise<string>;

export function DownloadLipReadingModel():Promise<string>;

export function EditMessage(arg1:number,arg2:string):Promise<main.ChatResponse>;

export function GetAudioDevice():Promise<string>;

export function GetAudioDevices():Promise<Array<voice.AudioDevice>>;

export function GetBetaLipReading():Promise<boolean>;

export function GetChatHistory():Promise<Array<main.ChatHistoryMessage>>;

export function GetComputerUseDisplay():Promise<string>;

export function GetComputerUseEnabled():Promise<boolean>;

export function GetComputerUseMonitor():Promise<number>;

export function GetCostSummary():Promise<llm.CostSummary>;

export function GetDefaultModel():Promise<string>;

export function GetEventSources():Promise<Array<string>>;

export function GetEventStats():Promise<eventbus.Stats>;

export function GetInstalledNames():Promise<Array<string>>;

export function GetLogPath():Promise<string>;

export function GetMCPServers():Promise<Array<main.MCPServerStatus>>;

export function GetMarketplace():Promise<Array<marketplace.CatalogEntry>>;

export function GetModels():Promise<Array<string>>;

export function GetNotificationsEnabled():Promise<boolean>;

export function GetProvider():Promise<string>;

export function GetProviders():Promise<Array<string>>;

export function GetSTTLanguage():Promise<string>;

export function GetSessions():Promise<Array<agent.SessionInfo>>;

export function GetTTSVoice():Promise<string>;

export function GetTTSVoices():Promise<Array<Record<string, any>>>;

export function GetVersion():Promise<string>;

export function GetVoiceEnabled():Promise<boolean>;

export function GetWakeListening():Promise<boolean>;

export function GetWakeWord():Promise<string>;

export function GetWatchedChats():Promise<Array<string>>;

export function GetWorkDir():Promise<string>;

export function HasAPIKey():Promise<boolean>;

export function InstallMarketplace(arg1:string,arg2:string):Promise<string>;

export function LipReadingModelReady():Promise<boolean>;

export function OpenAIIsLoggedIn():Promise<boolean>;

export function OpenAILogin():Promise<string>;

export function OpenPath(arg1:string):Promise<string>;

export function PiperSupported():Promise<boolean>;

export function ReauthMCPServer(arg1:string):Promise<string>;

export function RemoveMCPServer(arg1:string):Promise<string>;

export function ResetCosts():Promise<void>;

export function RespondPermission(arg1:string,arg2:boolean):Promise<void>;

export function ResumeSession(arg1:string):Promise<string>;

export function SendMessage(arg1:string):Promise<main.ChatResponse>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetAudioDevice(arg1:string):Promise<void>;

export function SetBetaLipReading(arg1:boolean):Promise<void>;

export function SetComputerUseDisplay(arg1:string):Promise<void>;

export function SetComputerUseEnabled(arg1:boolean):Promise<void>;

export function SetComputerUseMonitor(arg1:number):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetProvider(arg1:string):Promise<void>;

export function SetSTTLanguage(arg1:string):Promise<void>;

export function SetTTSVoice(arg1:string):Promise<string>;

export function SetVoiceEnabled(arg1:boolean):Promise<void>;

export function SetWakeListening(arg1:boolean):Promise<string>;

export function SetWakePaused(arg1:boolean):Promise<void>;

export function SetWakeWord(arg1:string):Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;

export function SpeakText(arg1:string):Promise<Record<string, any>>;

export function StartLipRecording():Promise<string>;

export function StartRecording():Promise<string>;

export function StopLipRecording():Promise<Record<string, any>>;

export function StopRecording():Promise<Record<string, any>>;

export function ToggleNotifications(arg1:boolean):Promise<void>;

export function TrackSentMessageID(arg1:string):Promise<void>;

export function TranscribeAudio(arg1:string):Promise<Record<string, any>>;

export function UnwatchChat(arg1:string):Promise<string>;

export function WatchChat(arg1:string):Promise<string>;
